%--------------------------------------------------------------------------
%This function takes the states and produces the basis vectors and the
%energy in them
%Usage:[F,E]=cpmdecomp(Sx,p)
%Sx:matrix of states generated by statewave
%p:fraction of energy required
%F:the basis vectors required for demodulation
%E:the actual fraction of energy contained in F
%--------------------------------------------------------------------------

function [F,E]=cpmdecomp(Sx,p)
[U,S,V]=svd(Sx);

%compute total energy
e=0;
for i=1:min(size(S))
    e=e+(S(i,i)^2);
end

%compute number of vectors to be returnd for suboptimal decoding
er=0;
vcount=0;
for i=1:min(size(S))
    frac=er/e;
    if(frac < p)
        er=er+(S(i,i)^2);
        vcount=vcount+1;
    end
end

F=U(1:vcount,:);
E=er/e;
end